config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  concern :with_autocomplete do
    get "autocomplete", on: :collection
  end

  concern :with_update_table do
    get "update_table", on: :collection
  end

  namespace :cadastro_basicos do
    resources :enderecos, concerns: [:with_autocomplete, :with_update_table]
    resources :municipes, concerns: [:with_autocomplete, :with_update_table]
    resources :tbperfis, concerns: [:with_autocomplete, :with_update_table]
    resources :tbpermissoes, concerns: [:with_autocomplete, :with_update_table]

  end

  resources :audits, path: :auditoria, only: [:index]


  namespace :site do
    get 'home/index'
  end
  namespace :backoffice do
    get 'dashboard/index'
    get 'dashboard/inscricoes'

  end

  #para acessar apenas por backoffice
  get 'backoffice', to: 'backoffice/dashboard#index'

  resources :admin_usuarios, concerns: [:with_autocomplete] do
    get :inativar_admin, on: :member
  end

  # devise_for :admins
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  #root quando acessar sem especificar rota alguma
  root 'backoffice/dashboard#index'

end

app/views/layouts/backoffice_admin/_footer.html.erb
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

<!-- Main Footer -->
<footer class="main-footer hidden-print">
  <strong>Copyright &copy; 2014-2021 <a href="#">Avaliação</a>.</strong>
  All rights reserved.
  <div class="float-right d-none d-sm-inline-block">
    <b>Version</b> 0.0.1
  </div>
</footer>

app/views/layouts/backoffice_admin/_navbar.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
  </ul>



  <% if @campeonatos.present? %>
    <%= form_tag(nil, method: :get) do %>
      <%= select_tag(:cdg_campeonato, options_from_collection_for_select(@campeonatos, "id", "nme_campeonato", cdg_campeonato_selecionado),
                     include_blank: "Selecione um campeonato", class: "select-estado select2", style: "min-height: unset; width: 400px") %>
    <% end %>
  <% end %>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link", title: 'Deslogar', data: { confirm: 'Deseja deslogar?' } do %>
        <i class="fas fa-sign-out-alt"></i>
      <% end %>
    </li>
  </ul>
</nav>
<!-- /.navbar -->

app/views/layouts/backoffice_admin/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <%= link_to root_path,
              class: "brand-link",
              title: "Home" do %>
    <!--    <img src="<%#= asset_path('AdminLTELogo.png') %>" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">-->
    <img class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">Avaliação</span>
  <% end %>

  <a href="index3.html" class="brand-link">
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <!--      <div class="image">-->
      <!--        <img src="<%#= asset_path('user2-160x160.jpg') %>" class="img-circle elevation-2" alt="User Image">-->
      <!--      </div>-->
      <div class="info">
        <span style="color: white"><%= current_admin.name %></span>
      </div>
    </div>

    <!-- SidebarSearch Form -->
    <div class="form-inline">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Procurar" aria-label="Procurar">
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->

        <% if can? :manage, Audit %>
          <li class="nav-item">
            <%= link_to audits_path, class: "nav-link breadcrumb-audits" do %>
              <i class="fas fa-fingerprint nav-icon"></i>
              <p>Auditoria</p>
            <% end %>
          </li>
        <% end %>

        <% if can? :manage, CadastroBasicos::Municipe %>
          <li class="nav-item">
            <%= link_to cadastro_basicos_municipes_path, class: "nav-link breadcrumb-campeonatos" do %>
              <i class="fas fa-trophy nav-icon"></i>
              <p>Municipes</p>
            <% end %>
          </li>
        <% end %>




          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-cogs"></i>
              <p>
                Cadastro Básicos
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">

              <% if can? :manage, CadastroBasicos::Endereco %>
                <li class="nav-item">
                  <%= link_to cadastro_basicos_enderecos_path, class: "nav-link breadcrumb-campeonatos" do %>
                    <i class="fas fa-trophy nav-icon"></i>
                    <p>Endereços</p>
                  <% end %>
                </li>
              <% end %>


              <% if can? :manage, CadastroBasicos::Tbpermissao %>
                <li class="nav-item">
                  <%= link_to cadastro_basicos_tbpermissoes_path, class: "nav-link breadcrumb-tbpermissoes" do %>
                    <i class="far fa-circle nav-icon"></i>
                    <p>Permissões</p>
                  <% end %>
                </li>
              <% end %>

              <% if can? :manage, AdminUsuario %>
                <li class="nav-item">
                  <%= link_to cadastro_basicos_tbperfis_path, class: "nav-link breadcrumb-tbperfil" do %>
                    <i class="far fa-circle nav-icon"></i>
                    <p>Perfils</p>
                  <% end %>
                </li>
              <% end %>



              <% if can? :manage, AdminUsuario %>
                <li class="nav-item">
                  <%= link_to admin_usuarios_path, class: "nav-link breadcrumb-admin-usuarios" do %>
                    <i class="far fa-circle nav-icon"></i>
                    <p>Usuários</p>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>


      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>