config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  concern :with_autocomplete do
    get "autocomplete", on: :collection
  end

  concern :with_update_table do
    get "update_table", on: :collection
  end

  namespace :cadastro_basicos do
    resources :enderecos, concerns: [:with_autocomplete, :with_update_table]
    resources :municipes, concerns: [:with_autocomplete, :with_update_table]
    resources :tbperfis, concerns: [:with_autocomplete, :with_update_table]
    resources :tbpermissoes, concerns: [:with_autocomplete, :with_update_table]

  end

  resources :audits, path: :auditoria, only: [:index]


  namespace :site do
    get 'home/index'
  end
  namespace :backoffice do
    get 'dashboard/index'
    get 'dashboard/inscricoes'

  end

  #para acessar apenas por backoffice
  get 'backoffice', to: 'backoffice/dashboard#index'

  resources :admin_usuarios, concerns: [:with_autocomplete] do
    get :inativar_admin, on: :member
  end

  # devise_for :admins
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  #root quando acessar sem especificar rota alguma
  root 'backoffice/dashboard#index'

end

app/models/admin_usuario.rb
class AdminUsuario < ApplicationRecord
  audited
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  self.table_name = 'admins'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :password, length: { in: 6..20 }, on: :create
  validates_presence_of :name, length: { minimum: 2 }


  has_many :cadastro_basicos_tbperfilusuarios, :class_name => 'CadastroBasicos::Tbperfilusuario',
           foreign_key: :admin_id, dependent: :destroy
  has_many :admins, :class_name => 'Admin', through: :cadastro_basicos_tbperfilusuarios
  accepts_nested_attributes_for :cadastro_basicos_tbperfilusuarios, allow_destroy: true

  def self.set_current_user
    Current.admin.id
  end

  def self.user_atual
    AdminUsuario.find(Current.admin.id)
  end

  enum kind: { comum: 0, gestor: 1 }



  private




end

app/controllers/admin_usuarios_controller.rb
class AdminUsuariosController < BackofficeController
  before_action :autorizacao
  before_action :set_admin, only: [:show, :edit, :update, :destroy, :inativar_admin]
  # load_and_authorize_resource except: :create
  before_action :add_breadcrumb_modulo

  def index
    session[:cdg_estado] = params[:cdg_estado] || session[:cdg_estado]
    @q = AdminUsuario.all.ransack(params[:q])
    @admin = @q.result.page(params[:page])
  end

  def show
    add_breadcrumb label_translate(:show)
  end

  def new
    add_breadcrumb label_translate(:new)
    @admin = AdminUsuario.new
  end

  def edit
    add_breadcrumb label_translate(:edit)
  end

  def create
    @admin = AdminUsuario.new(admin_params)
    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
        format.js { render 'shared/show_messages' }
      end
    end
  end

  def update
    if params[:admin_usuario][:password].blank? && params[:admin_usuario][:password_confirmation].blank?
      params[:admin_usuario].extract!(:password, :password_confirmation)
    end
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
        format.js { render 'shared/show_messages' }
      end
    end
  end

  def destroy
    @admin.destroy
  end

  def inativar_admin
    @admin.update!(active: false, email: "inativo" + @admin.email, password: 'inativo123')
  end



  private

  def set_admin
    @admin = AdminUsuario.find(params[:id])
  end

  def admin_params
    params.require(:admin_usuario).permit(:id, :email, :kind, :cpf, :name, :date_birth, :date_register, :active, :password, :reset_password_token,
                                          admin_cidades_attributes: [:id, :admin_id, :admin_usuario_id, :cidade_id, :_destroy],
                                          cadastro_basicos_tbperfilusuarios_attributes: [:id, :admin_id, :tbperfil_id, :_destroy],
                                          admin_cidade_attributes: [:id, :admin_id, :cidade_id, :_destroy],
                                          admins_attributes: [:id, :email, :_destroy])
  end

  def add_breadcrumb_modulo
    add_breadcrumb "Admin"
  end

  def autorizacao
    redirect_to_permission unless can? :manage, AdminUsuario
  end
end

app/views/admin_usuarios/_form.html.erb
<% if @admin.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@admin.errors.count, "erro") %> proibiu esta ação</h2>
    <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>



<div class="modal-content">
  <%= bootstrap_form_for @admin,
                         remote: true,
                         id: 'tbadmin_usuario_create', html: { role: 'form' } do |f| %>
    <div class="modal-header">
      <h4 class="modal-title" id="modal_titulo"></h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.text_field :name, class: "form-control", type: "text", placeholder: "Nome completo" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label>Apelido</label>
            <input type="text" class="form-control" placeholder="Apelido">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.text_field :email, class: "form-control", type: "text", placeholder: "E-mail" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label>Número de contato</label>
            <input type="text" class="form-control" placeholder="Numero">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.text_field :cpf, class: "form-control", type: "text", placeholder: "Número do cpf" %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <label>Aniversário</label>
            <input class="form-control" type="date" value="2011-08-19" id="example-date-input">
          </div>
        </div>


      </div>


      <div class="row">

        <div class="col-md-6">
          <div class="form-group">
            <%= f.password_field :password, class: "form-control", autocomplete: "new-password" %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <%= f.password_field :password_confirmation, class: "form-control", autocomplete: "new-password" %>
          </div>
        </div>

      </div>

      <div class="row">



      </div>


      <hr class="my-15">
      <div class="row">
        <div class="col-md-10"></div>
        <div class="col-md-2">
          <%= link_to_add_association "<i class='fa fa-plus'></i> Perfils".html_safe,
                                      f, :cadastro_basicos_tbperfilusuarios,
                                      'data-association-insertion-node' => "#admin-div",
                                      'data-association-insertion-method' => "append",
                                      partial: 'admin_usuarios/tbperfilusuario_fields',
                                      class: "btn btn-block btn-info", style: 'color:#fff' %>
        </div>
      </div>
      <hr>
      <div class="row margin-bottom-10">
        <div class="col-md-10"><b>Perfils</b></div>
        <div class="col-md-2 text-align-center">Ações</div>
      </div>
      <div id="admin-div">
        <%= f.fields_for :cadastro_basicos_tbperfilusuarios do |f| %>
          <% render 'admin_usuarios/tbperfilusuario_fields', f: f %>
        <% end %>
      </div>


    </div>
    <div class="modal-footer justify-content-between">
      <button type="button" class="btn btn-default" data-dismiss="modal"><%= label_translate(:cancel) %></button>
      <button type="submit" class="btn btn-primary"><%= label_translate(:save) %></button>
    </div>
  <% end %>
</div>






		

app/views/admin_usuarios/_show.html.erb
<div class="modal-content">
  <div class="modal-header">
    <h4 class="modal-title" id="modal_titulo"></h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
  <div class="modal-body">
    <table class="table">
      <tr>
        <th width="10%" style="text-align: right;">
          <b><%= translate_attr(AdminUsuario, :nome) %>:</b></th>

        <td><%= h @admin.nome %></td>
      </tr>

    </table>
  </div>
  <div class="modal-footer">
    <div class="pull-left">
      <button type="button" id="btnFechar" class="btn btn-white" data-dismiss="modal"><%= label_translate(:close) %></button>
    </div>
  </div>
</div>

app/views/admin_usuarios/_tbperfilusuario_fields.html.erb
<div class="nested-fields" id="tab_<%= f.index %>">
  <div class="row">
    <div class="col-md-10">
      <%= h f.select :tbperfil_id,
                     options_for_select(CadastroBasicos::Tbperfil.all.collect { |p| ["#{p.nome}", p.id] },
                                        selected: f.object.tbperfil_id),
                     { include_blank: "Selecione um perfil para o usuário",
                       hide_label: true },
                     { class: 'form-control select2',
                       style: "width: 100%;" } %>
    </div>
    <div class="col-md-2 text-align-center">
      <%= link_to_remove_association "Remover", f, class: "btn btn-danger btn-sm" %>
    </div>
  </div>
</div>
<script>
    resetarComponents();
</script>

app/views/admin_usuarios/create.js.erb
<% if @admin.errors.size > 0 %>
    if ($('#error_explanation').length > 0)
        $('#error_explanation').html('<%= escape_javascript(render 'layouts/error_messages', objeto: @admin) %>');
else {
    toastr.warning('<%= specific_alert(:unsuccess_created) %>');
}
<% else %>
$('#modal_xfull_static').modal('hide');
location.reload();
toastr.success('<%= specific_alert(:success_created) %>');
<% end %>

app/views/admin_usuarios/destroy.js.erb
<% if @admin.errors.size > 0 %>
    if ($('#error_explanation').length > 0)
        $('#error_explanation').html('<%= escape_javascript(render 'layouts/error_messages', objeto: @admin) %>');
else {
    toastr.warning('<%= specific_alert(:unsuccess_destroyed) %>');
}
<% else %>
location.reload();
toastr.success('<%= specific_alert(:success_destroyed) %>');
<% end %>

app/views/admin_usuarios/edit.html.erb
<%= render partial: "admin_usuarios/shared/form", locals: {title: "Usuários", subtitle: "Editar usuário #{@admin.name}"} %>

app/views/admin_usuarios/edit.js.erb
$('#modal_xfull_static').modal();
$("#modal_content_xfull_static").html("<%= escape_javascript(render('form')) %>");

// Add the dialog title
$('#modal_titulo').html("<%= label_translate(:edit) %> <%= singularize_model(AdminUsuario) %>");
resetarComponents();

app/views/admin_usuarios/inativar_admin.js.erb
$('#admin_datatable_id').dataTable()._fnAjaxUpdate();

app/views/admin_usuarios/index.html.erb
<section class="content-header">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i> Home</a></li>
    <li class="breadcrumb-item"><a href="#">Cadastro Básicos</a></li>
    <li class="breadcrumb-item active" data-breadcrumb="admin-usuarios"><%= translate_model(AdminUsuario) %></li>
  </ol>
</section>


<section class="content">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">Listagem de <%= pluralize_model(AdminUsuario) %> </h3>
      <div class="card-tools">
        <%= link_to new_admin_usuario_path, class: 'btn btn-primary btn-sm btn-block', remote: true do %>
          <i class="fa fa-plus"></i> Novo
        <% end %>
      </div>
    </div>
    <div class="card-body">
      <%= search_form_for @q do |f| %>
        <div class="row margin-bottom-15">
          <div class="col-md-3">
            <%= h f.label :name %>
            <%= h f.text_field :name_cont, class: 'form-control',
                               autocomplete: 'off',
                               placeholder: "Digite o #{translate_attr(AdminUsuario, :name)}" %>
          </div>


          <div class="col-md-1">
            <%= button_tag(type: "submit", class: "btn btn-primary btn-block bottom-div ", data: { disable_with: "Filtrando..." }) do %>
              <i class="fas fa-search"></i> Filtrar
            <% end %>
          </div>
        </div>
      <% end %>
      <table class="table table-bordered table-striped datatable">
        <thead>
        <tr>
          <th><%= translate_attr(AdminUsuario, :name) %></th>
          <th><%= translate_attr(AdminUsuario, :email) %></th>

          <th><%= translate_attr(AdminUsuario, :active) %></th>
          <th>Ações</th>
        </tr>
        </thead>
        <tbody id="table-cadastro_basicos_tbciclo">
        <% @admin.each do |dado| %>
          <tr>
            <td><%= dado.name %></td>
            <td><%= dado.email %></td>
            <td><%= dado.active %></td>
            <td class="white-space-nowrap-center" style="width: 16px">
              <%= link_to_visualizar admin_usuario_path(dado), remote: true %>
              <%= link_to_editar edit_admin_usuario_path(dado), remote: true %>
              <%= link_to_excluir admin_usuario_path(dado), remote: true %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= page_entries_info @admin %>
      <%= paginate @admin, outer_window: 2 %>
    </div>
  </div>
</section>

app/views/admin_usuarios/new.html.erb
<%= render partial: "admin_usuarios/shared/form", locals: {title: "Usuários", subtitle: "Criar um novo usuário"} %>

app/views/admin_usuarios/new.js.erb
$('#modal_xfull_static').modal();
$("#modal_content_xfull_static").html("<%= escape_javascript(render('form')) %>");

// Add the dialog title
$('#modal_titulo').html("<%= label_translate(:new) + ' ' + singularize_model(AdminUsuario) %>");
resetarComponents();

app/views/admin_usuarios/show.html.erb
<section class="content-header">
  <h1>
    General Form Elements
  </h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i> Home</a></li>
    <li class="breadcrumb-item"><a href="#">Forms</a></li>
    <li class="breadcrumb-item active">General Elements</li>
  </ol>
</section>

<section class="content">

    <div class="box box-solid bg-gray">
      <div class="box-header with-border">
        <h4 class="box-title">Vizualização Usuário</h4>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <div class="table-responsive">
          <table class="table table-bordered mb-0">
            <tbody>
            <tr>
              <th width="10%" scope="col">Nome</th>
              <th><%= @admin.name %></th>
            </tr>
            <tr>
              <th scope="col">Email</th>
              <td><%= @admin.email %></td>
            </tr>

            <tr>
              <th scope="col">Cpf</th>
              <td><%= @admin.cpf %></td>
            </tr>
            <tr>
              <th scope="col">Data nasc</th>
              <td><%= @admin.date_birth %></td>
            </tr>

            </tbody>
          </table>
        </div>
        <div class="box-footer">
          <%= link_to url_for(:back), type: "button", class: "btn btn-warning btn-outline mr-1" do %>
            <i class="ti-trash"></i> Cancel
          <% end %>
          <%= link_to edit_admin_usuario_path(@admin), type: "submit", class: "btn btn-primary btn-outline" do %>
            <i class="ti-save-alt"></i> Editar
          <% end %>
        </div>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->

</section>

app/views/admin_usuarios/show.js.erb
$('#modal_xfull_static').modal();
$("#modal_content_xfull_static").html("<%= escape_javascript(render('show')) %>");

// Add the dialog title
$('#modal_titulo').html("<%= label_translate(:show) %> <%= singularize_model(AdminUsuario) %>");

app/views/admin_usuarios/update.js.erb
<% if @admin.errors.size > 0 %>
    if ($('#error_explanation').length > 0)
        $('#error_explanation').html('<%= escape_javascript(render 'layouts/error_messages', objeto: @admin) %>');
else {
    toastr.warning('<%= specific_alert(:unsuccess_updated) %>');
}
<% else %>

$('#modal_xfull_static').modal('hide');
location.reload();
toastr.success('<%= specific_alert(:success_updated) %>');
<% end %>