config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  concern :with_autocomplete do
    get "autocomplete", on: :collection
  end

  concern :with_update_table do
    get "update_table", on: :collection
  end

  namespace :cadastro_basicos do
    resources :enderecos, concerns: [:with_autocomplete, :with_update_table]
    resources :municipes, concerns: [:with_autocomplete, :with_update_table]
    resources :tbperfis, concerns: [:with_autocomplete, :with_update_table]
    resources :tbpermissoes, concerns: [:with_autocomplete, :with_update_table]

  end

  resources :audits, path: :auditoria, only: [:index]


  namespace :site do
    get 'home/index'
  end
  namespace :backoffice do
    get 'dashboard/index'
    get 'dashboard/inscricoes'

  end

  #para acessar apenas por backoffice
  get 'backoffice', to: 'backoffice/dashboard#index'

  resources :admin_usuarios, concerns: [:with_autocomplete] do
    get :inativar_admin, on: :member
  end

  # devise_for :admins
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  #root quando acessar sem especificar rota alguma
  root 'backoffice/dashboard#index'

end

app/models/backoffice/cadastro_basico.rb
module Backoffice::CadastroBasico
  def self.table_name_prefix
    'backoffice_cadastro_basico_'
  end
end

app/models/backoffice/cadastro_basicos.rb
module Backoffice::CadastroBasicos
  def self.table_name_prefix
    'backoffice_cadastro_basicos_'
  end
end

app/models/cadastro_basicos.rb
module CadastroBasicos
  def self.table_name_prefix
    'cadastro_basicos_'
  end
end

app/models/cadastro_basicos/endereco.rb
# frozen_string_literal: true

class CadastroBasicos::Endereco < ApplicationRecord
  # main config ...............................................................
  self.table_name = "tbenderecos"
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :cadastro_basicos_municipe, class_name: 'CadastroBasicos::Municipe', optional: true


  # validations ...............................................................
    validates_presence_of  :cep, :logradouro, :bairro, :cidade, :uf
    # callbacks .................................................................
    # scopes ....................................................................

    # Scope para consulta
    scope :like, -> (value) do
      where(<<-SQL.squish, q: "%#{value.upcase}%").order(:descricao).limit(TOTAL_REGISTROS)
       upper(#{SCHEMA_NAME}.fu_sem_acentos(descricao)) like upper(#{SCHEMA_NAME}.fu_sem_acentos(:q))
          or to_char(id) like (:q)
      SQL
    end

    # additional config .........................................................
        # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
    # codigo e nome
    def codigo_descricao
      "#{self.descricao&.upcase} (#{self.id})"
    end

  end

app/models/cadastro_basicos/municipe.rb
# frozen_string_literal: true

class CadastroBasicos::Municipe < ApplicationRecord
  audited
  # main config ...............................................................
  self.table_name = "tbmunicipes"
  # extends ...................................................................
  # includes ..................................................................
  include RemoveFormatoConcern
  include ValidaCpfCnpjConcern
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :cadastro_basicos_enderecos, :class_name => 'CadastroBasicos::Endereco',
           foreign_key: :municipes_id, dependent: :destroy
  accepts_nested_attributes_for :cadastro_basicos_enderecos, allow_destroy: true



  attr_accessor :foto
  has_one_attached :foto, :dependent => :destroy

  # validations ...............................................................
  validates_presence_of :nome_completo, :cpf, :cns, :email, :dta_nascimento, :telefone, :foto, :status
  validates_length_of :cns, :minimum => 5
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :dta_nascimento,
            inclusion: { in: 65.years.ago..18.years.ago }
  # callbacks .................................................................
  # scopes ....................................................................

  # Scope para consulta
  scope :like, -> (value) do
    where(<<-SQL.squish, q: "%#{value.upcase}%").order(:descricao).limit(TOTAL_REGISTROS)
       upper(#{SCHEMA_NAME}.fu_sem_acentos(descricao)) like upper(#{SCHEMA_NAME}.fu_sem_acentos(:q))
          or to_char(id) like (:q)
    SQL
  end



  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  # codigo e nome
  def codigo_descricao
    "#{self.descricao&.upcase} (#{self.id})"
  end

end

app/controllers/cadastro_basicos/application_controller.rb
class CadastroBasicos::ApplicationController < BackofficeController
  before_action :authenticate_admin! #para direcionar a rota para logar caso n esteja logado
end

app/controllers/cadastro_basicos/enderecos_controller.rb
# frozen_string_literal: true

class CadastroBasicos::EnderecosController < CadastroBasicos::ApplicationController
  before_action :set_cadastro_basicos_endereco, only: %i(show edit update destroy)
  before_action :add_breadcrumb_modulo

  # GET /cadastro_basicos/enderecos
  # Visualizar CadastroBasicos::Endereco
  def index

    @cadastro_basicos_enderecos = CadastroBasicos::Endereco.all.page(params[:page])
  end

  # GET /cadastro_basicos/enderecos/1
  # Visualizar CadastroBasicos::Endereco
  def show
    add_breadcrumb label_translate(:show)
  end

  # GET /cadastro_basicos/enderecos/new
  # Novo CadastroBasicos::Endereco
  def new
    add_breadcrumb label_translate(:new)
    @cadastro_basicos_endereco = CadastroBasicos::Endereco.new
  end

  # GET /cadastro_basicos/enderecos/1/edit
  # Editar CadastroBasicos::Endereco
  def edit
    add_breadcrumb label_translate(:edit)
  end

  # POST /cadastro_basicos/enderecos
  # Criar CadastroBasicos::Endereco
  def create
    @cadastro_basicos_endereco = CadastroBasicos::Endereco.new(cadastro_basicos_endereco_params)
    @cadastro_basicos_endereco.save
  end

  # PATCH/PUT /cadastro_basicos/enderecos/1
  # Atualizar CadastroBasicos::Endereco
  def update
    @cadastro_basicos_endereco.update(cadastro_basicos_endereco_params)
  end

  # DELETE /cadastro_basicos/enderecos/1
  # Excluir CadastroBasicos::Endereco
  def destroy
    @cadastro_basicos_endereco.destroy
  end

  # Retorna um resultado de consulta para o autocomplete
  def autocomplete
    if params[:key].present?
      @lista_dados = CadastroBasicos::Endereco.find(params[:key])
    else
      @lista_dados = CadastroBasicos::Endereco.like(params[:q])
    end
    render json: @lista_dados.as_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro_basicos_endereco
      @cadastro_basicos_endereco = CadastroBasicos::Endereco.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cadastro_basicos_endereco_params
      params.require(:cadastro_basicos_endereco).permit(:cep, :logradouro, :complemento, :bairro, :cidade, :uf, :cod_ibge)
    end

    # Adiciona Breadcrumb geral para o controller
    def add_breadcrumb_modulo
      add_breadcrumb translate_model(CadastroBasicos::Endereco), cadastro_basicos_enderecos_path
    end
end

app/controllers/cadastro_basicos/municipes_controller.rb
# frozen_string_literal: true

class CadastroBasicos::MunicipesController < CadastroBasicos::ApplicationController
  before_action :set_cadastro_basicos_municipe, only: %i(show edit update destroy)
  before_action :add_breadcrumb_modulo

  # GET /cadastro_basicos/municipes
  # Visualizar CadastroBasicos::Municipe
  def index
    @q = CadastroBasicos::Municipe.eager_load(:cadastro_basicos_enderecos).ransack(params[:q])
    @cadastro_basicos_municipes = @q.result.page(params[:page])
  end

  # GET /cadastro_basicos/municipes/1
  # Visualizar CadastroBasicos::Municipe
  def show
    add_breadcrumb label_translate(:show)
  end

  # GET /cadastro_basicos/municipes/new
  # Novo CadastroBasicos::Municipe
  def new
    add_breadcrumb label_translate(:new)
    @cadastro_basicos_municipe = CadastroBasicos::Municipe.new
  end

  # GET /cadastro_basicos/municipes/1/edit
  # Editar CadastroBasicos::Municipe
  def edit
    add_breadcrumb label_translate(:edit)
  end

  # POST /cadastro_basicos/municipes
  # Criar CadastroBasicos::Municipe
  def create
    @cadastro_basicos_municipe = CadastroBasicos::Municipe.new(cadastro_basicos_municipe_params)
    if @cadastro_basicos_municipe.save
      redirect_to cadastro_basicos_municipes_path, success: translate_model(CadastroBasicos::Municipe) + flash_messages_translate(:successfully_created)
    else
      render action: "new"
    end

  end

  # PATCH/PUT /cadastro_basicos/municipes/1
  # Atualizar CadastroBasicos::Municipe
  def update

    if @cadastro_basicos_municipe.update(cadastro_basicos_municipe_params)
      redirect_to cadastro_basicos_municipes_path, success: translate_model(CadastroBasicos::Municipe) + flash_messages_translate(:successfully_created)
    else
      render action: "edit"
    end
  end

  # DELETE /cadastro_basicos/municipes/1
  # Excluir CadastroBasicos::Municipe
  def destroy
    @cadastro_basicos_municipe.destroy
  end

  # Retorna um resultado de consulta para o autocomplete
  def autocomplete
    if params[:key].present?
      @lista_dados = CadastroBasicos::Municipe.find(params[:key])
    else
      @lista_dados = CadastroBasicos::Municipe.like(params[:q])
    end
    render json: @lista_dados.as_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro_basicos_municipe
      @cadastro_basicos_municipe = CadastroBasicos::Municipe.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cadastro_basicos_municipe_params
      params.require(:cadastro_basicos_municipe).permit(:nome_completo, :cpf, :cns, :email, :dta_nascimento, :telefone, :foto, :status,
                                                        cadastro_basicos_enderecos_attributes: [:id, :cep, :logradouro, :bairro, :cidade, :uf, :_destroy])
    end

    # Adiciona Breadcrumb geral para o controller
    def add_breadcrumb_modulo
      add_breadcrumb translate_model(CadastroBasicos::Municipe), cadastro_basicos_municipes_path
    end
end

app/controllers/cadastro_basicos/tbperfis_controller.rb
# frozen_string_literal: true

class CadastroBasicos::TbperfisController < CadastroBasicos::ApplicationController
  before_action :autorizacao
  before_action :set_cadastro_basicos_tbperfil, only: %i(show edit update destroy)
  before_action :add_breadcrumb_modulo

  # GET /cadastro_basicos/tbperfis
  # Visualizar CadastroBasicos::Tbperfil
  def index

    @cadastro_basicos_tbperfis = CadastroBasicos::Tbperfil.all.page(params[:page])
  end

  # GET /cadastro_basicos/tbperfis/1
  # Visualizar CadastroBasicos::Tbperfil
  def show
    add_breadcrumb label_translate(:show)
  end

  # GET /cadastro_basicos/tbperfis/new
  # Novo CadastroBasicos::Tbperfil
  def new
    add_breadcrumb label_translate(:new)
    @cadastro_basicos_tbperfil = CadastroBasicos::Tbperfil.new
  end

  # GET /cadastro_basicos/tbperfis/1/edit
  # Editar CadastroBasicos::Tbperfil
  def edit
    add_breadcrumb label_translate(:edit)
  end

  # POST /cadastro_basicos/tbperfis
  # Criar CadastroBasicos::Tbperfil
  def create
    @cadastro_basicos_tbperfil = CadastroBasicos::Tbperfil.new(cadastro_basicos_tbperfil_params)
    @cadastro_basicos_tbperfil.save
  end

  # PATCH/PUT /cadastro_basicos/tbperfis/1
  # Atualizar CadastroBasicos::Tbperfil
  def update
    @cadastro_basicos_tbperfil.update(cadastro_basicos_tbperfil_params)
  end

  # DELETE /cadastro_basicos/tbperfis/1
  # Excluir CadastroBasicos::Tbperfil
  def destroy
    @cadastro_basicos_tbperfil.destroy
  end

  # Retorna um resultado de consulta para o autocomplete
  def autocomplete
    if params[:key].present?
      @lista_dados = CadastroBasicos::Tbperfil.find(params[:key])
    else
      @lista_dados = CadastroBasicos::Tbperfil.like(params[:q])
    end
    render json: @lista_dados.as_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro_basicos_tbperfil
      @cadastro_basicos_tbperfil = CadastroBasicos::Tbperfil.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cadastro_basicos_tbperfil_params
      params.require(:cadastro_basicos_tbperfil).permit(:nome, :ativo, :chave,
                                                        cadastro_basicos_tbperfil_tbpermissaos_attributes: [:id, :tbpermissao_id,
                                                                                                                :tbperfil_id,
                                                                                                                :_destroy],
                                                        cadastro_basicos_tbperfilusuarios_attributes: [:id, :admin_id,
                                                                                                            :tbperfil_id,
                                                                                                            :_destroy])
    end

    # Adiciona Breadcrumb geral para o controller
    def add_breadcrumb_modulo
      add_breadcrumb translate_model(CadastroBasicos::Tbperfil), cadastro_basicos_tbperfis_path
    end

 def autorizacao
   redirect_to_permission unless can? :manage, CadastroBasicos::Tbperfil
  end
end

app/controllers/cadastro_basicos/tbpermissoes_controller.rb
# frozen_string_literal: true

class CadastroBasicos::TbpermissoesController < CadastroBasicos::ApplicationController
  before_action :autorizacao
  before_action :set_cadastro_basicos_tbpermissao, only: %i(show edit update destroy)
  before_action :add_breadcrumb_modulo

  # GET /cadastro_basicos/tbpermissoes
  # Visualizar CadastroBasicos::Tbpermissao
  def index

    @cadastro_basicos_tbpermissoes = CadastroBasicos::Tbpermissao.all.page(params[:page])
  end

  # GET /cadastro_basicos/tbpermissoes/1
  # Visualizar CadastroBasicos::Tbpermissao
  def show
    add_breadcrumb label_translate(:show)
  end

  # GET /cadastro_basicos/tbpermissoes/new
  # Novo CadastroBasicos::Tbpermissao
  def new
    add_breadcrumb label_translate(:new)
    @cadastro_basicos_tbpermissao = CadastroBasicos::Tbpermissao.new
  end

  # GET /cadastro_basicos/tbpermissoes/1/edit
  # Editar CadastroBasicos::Tbpermissao
  def edit
    add_breadcrumb label_translate(:edit)
  end

  # POST /cadastro_basicos/tbpermissoes
  # Criar CadastroBasicos::Tbpermissao
  def create
    @cadastro_basicos_tbpermissao = CadastroBasicos::Tbpermissao.new(cadastro_basicos_tbpermissao_params)
    @cadastro_basicos_tbpermissao.save
  end

  # PATCH/PUT /cadastro_basicos/tbpermissoes/1
  # Atualizar CadastroBasicos::Tbpermissao
  def update
    @cadastro_basicos_tbpermissao.update(cadastro_basicos_tbpermissao_params)
  end

  # DELETE /cadastro_basicos/tbpermissoes/1
  # Excluir CadastroBasicos::Tbpermissao
  def destroy
    @cadastro_basicos_tbpermissao.destroy
  end

  # Retorna um resultado de consulta para o autocomplete
  def autocomplete
    if params[:key].present?
      @lista_dados = CadastroBasicos::Tbpermissao.find(params[:key])
    else
      @lista_dados = CadastroBasicos::Tbpermissao.like(params[:q])
    end
    render json: @lista_dados.as_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro_basicos_tbpermissao
      @cadastro_basicos_tbpermissao = CadastroBasicos::Tbpermissao.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cadastro_basicos_tbpermissao_params
      params.require(:cadastro_basicos_tbpermissao).permit(:classe, :acao, :nome, :permissao_pai, :ativo, :chave)
    end

    # Adiciona Breadcrumb geral para o controller
    def add_breadcrumb_modulo
      add_breadcrumb translate_model(CadastroBasicos::Tbpermissao), cadastro_basicos_tbpermissoes_path
    end

  def autorizacao
    redirect_to_permission unless can? :manage, CadastroBasicos::Tbpermissao
  end
end

app/views/cadastro_basicos/municipes/_endereco_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3><strong><%= translate_model(CadastroBasicos::Endereco) %></strong></h3>
          <div class="pull-right">
            <%#= link_to_remove_association "Remover", f, class: "btn btn-danger btn-xs" %>
          </div>
        </div>
        <div class="panel-body padding-10">
          <div class="row">
            <div class="col-md-5">
              <%= h f.text_field :cep, class: 'form-control',
                                 label: translate_attr(CadastroBasicos::Endereco, :cep),
                                 placeholder: "Digite o #{translate_attr(CadastroBasicos::Endereco, :cep)}" %>

            </div>
            <div class="col-md-5">
              <%= h f.text_field :logradouro, class: 'form-control',
                                 label: translate_attr(CadastroBasicos::Endereco, :logradouro),
                                 placeholder: "Digite o #{translate_attr(CadastroBasicos::Endereco, :logradouro)}" %>

            </div>
            <div class="col-md-5">
              <%= h f.text_field :complemento, class: 'form-control',
                                 label: translate_attr(CadastroBasicos::Endereco, :complemento),
                                 placeholder: "Digite o #{translate_attr(CadastroBasicos::Endereco, :complemento)}" %>

            </div>
            <div class="col-md-5">
              <%= h f.text_field :bairro, class: 'form-control',
                                 label: translate_attr(CadastroBasicos::Endereco, :bairro),
                                 placeholder: "Digite o #{translate_attr(CadastroBasicos::Endereco, :bairro)}" %>

            </div>
            <div class="col-md-5">
              <%= h f.text_field :cidade, class: 'form-control',
                                 label: translate_attr(CadastroBasicos::Endereco, :cidade),
                                 placeholder: "Digite o #{translate_attr(CadastroBasicos::Endereco, :cidade)}" %>

            </div>
            <div class="col-md-5">
              <%= h f.label :uf %>
              <%= h f.select :uf,
                             options_for_select(ESTADOS_BRASILEIROS.collect { |p| [p[:label], p[:chave]] },
                                                selected: f.object.uf),
                             { include_blank: "Selecione um UF",
                               hide_label: true },
                             { class: 'form-control select2',
                               style: "width: 100%;" } %>



            </div>
            <div class="col-md-2 text-align-center">
              <%= link_to_remove_association "Remover", f, class: "btn btn-danger btn-sm" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
    resetarComponents();
</script>

app/views/cadastro_basicos/municipes/_form.html.erb
<section class="content-header">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i> Home</a></li>
    <li class="breadcrumb-item"><a href="#">Cadastro Básicos</a></li>
    <li class="breadcrumb-item active"><%= translate_model(CadastroBasicos::Municipe) %></li>
  </ol>
</section>

<section class="content">
  <div class="card">
    <div class="card-body">
      <%= bootstrap_form_for @cadastro_basicos_municipe,
                             id: 'municipes_create', html: { role: 'form', multipart: :true } do |f| %>
        <div class="col-md-12">
          <div class="form-body">
            <div id="error_explanation">
            </div>
            <%= f.alert_message specific_alert(:data_empty) %>

            <div class="row">
              <div class="col-md-4">
                <%= h f.text_field :nome_completo, class: 'form-control',
                                   label: translate_attr(CadastroBasicos::Municipe, :nome_completo),
                                   placeholder: "Digite o #{translate_attr(CadastroBasicos::Municipe, :nome_completo)}" %>

              </div>
              <div class="col-md-4">
                <%= h f.text_field :cpf, class: 'form-control',
                                   label: translate_attr(CadastroBasicos::Municipe, :cpf),
                                   placeholder: "Digite o #{translate_attr(CadastroBasicos::Municipe, :cpf)}" %>

              </div>
              <div class="col-md-4">
                <%= h f.text_field :cns, class: 'form-control',
                                   label: translate_attr(CadastroBasicos::Municipe, :cns),
                                   placeholder: "Digite o #{translate_attr(CadastroBasicos::Municipe, :cns)}" %>

              </div>
            </div>

            <div class="row">
              <div class="col-md-4">
                <%= h f.text_field :email, class: 'form-control',
                                   label: translate_attr(CadastroBasicos::Municipe, :email),
                                   placeholder: "Digite o #{translate_attr(CadastroBasicos::Municipe, :email)}" %>


              </div>
              <div class="col-md-4">
                <%= h f.text_field :dta_nascimento, class: 'form-control date-picker-single',
                                   id: 'dta-nascimento',
                                   value: format_data(f.object.dta_nascimento),
                                   label: translate_attr(CadastroBasicos::Municipe, :dta_nascimento),
                                   placeholder: "Digite o #{translate_attr(CadastroBasicos::Municipe, :dta_nascimento)}" %>
              </div>
              <div class="col-md-4">
                <%= h f.text_field :telefone, class: 'form-control celular',
                                   label: translate_attr(CadastroBasicos::Municipe, :telefone),
                                   placeholder: "Digite o #{translate_attr(CadastroBasicos::Municipe, :telefone)}" %>

              </div>
              <div class="col-md-2">
                <%= f.check_box :status, label: 'Ativado' %>
              </div>
            </div>

            <div class="row">
              <% if f.object.foto.attached? %>
                <%= image_tag f.object.foto.variant(resize: "100x100") %>
              <% end %>


              <div class="form-group">
                <%= f.file_field :foto, :presence => true, class: "form-control", :as => :file, id: "image_upload_id" %>
              </div>

            </div>


            <div id="endereco" class="cocoon-group">
              <%= f.fields_for :cadastro_basicos_enderecos do |enderecos_fields| %>
                <% render 'cadastro_basicos/municipes/endereco_fields', f: enderecos_fields %>
              <% end %>
            </div>

            <div class="row">
              <div class="col-md-12">
                <div class="pull-left">
                  <div class="links">
                    <%= link_to_add_association "Adicionar Endereço", f, :cadastro_basicos_enderecos,
                                                'data-association-insertion-method' => "prepend", partial: 'cadastro_basicos/municipes/endereco_fields',
                                                'data-association-insertion-node' => "#endereco",
                                                class: "btn btn-info btn-sm", style: "color: #FFF" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer justify-content-between">
          <button type="button" class="btn btn-default" data-dismiss="modal"><%= label_translate(:cancel) %></button>
          <button type="submit" class="btn btn-primary"><%= label_translate(:save) %></button>
        </div>
      <% end %>
    </div>
  </div>

</section>

app/views/cadastro_basicos/municipes/edit.html.erb
<%= panel_with_form title: label_translate(:edit) + translate_model(CadastroBasicos::Municipe) %>

app/views/cadastro_basicos/municipes/index.html.erb
<section class="content-header">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i> Home</a></li>
    <li class="breadcrumb-item"><a href="#">Cadastro Básicos</a></li>
    <li class="breadcrumb-item active"><%= translate_model(CadastroBasicos::Municipe) %></li>
  </ol>
</section>

<section class="content">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">Listagem de <%= translate_model(CadastroBasicos::Municipe) %> </h3>
      <div class="card-tools">
        <%= link_to new_cadastro_basicos_municipe_path, class: 'btn btn-primary btn-sm btn-block' do %>
          <i class="fa fa-plus"></i> Novo
        <% end %>
      </div>
    </div>
    <div class="card-body">

      <%= search_form_for @q do |f| %>
        <div class="row margin-bottom-15">
          <div class="col-md-3">
            <%= h f.label :nome_completo %>
            <%= h f.text_field :nome_completo_eq, class: 'form-control',
                               autocomplete: 'off',
                               placeholder: "Digite o #{translate_attr(CadastroBasicos::Municipe, :nome_completo)}" %>
          </div>

          <div class="col-md-1">
            <%= button_tag(type: "submit", class: "btn btn-primary btn-block bottom-div ", data: { disable_with: "Filtrando..." }) do %>
              <i class="fas fa-search"></i> Filtrar
            <% end %>
          </div>
        </div>
      <% end %>


      <table class="table table-bordered table-striped datatable">
        <thead>
        <tr>
          <th>Código</th>

          <th><%= translate_attr(CadastroBasicos::Municipe, :nome_completo) %></th>

          <th><%= translate_attr(CadastroBasicos::Municipe, :cpf) %></th>

          <th><%= translate_attr(CadastroBasicos::Municipe, :cns) %></th>

          <th><%= translate_attr(CadastroBasicos::Municipe, :email) %></th>


          <th>Ações</th>
        </tr>
        </thead>
        <tbody id="table-cadastro_basicos_municipe">
        <% @cadastro_basicos_municipes.each do |dado| %>
          <tr>
            <td><%= dado.id %></td>

            <td><%= dado.nome_completo %></td>

            <td><%= dado.cpf %></td>

            <td><%= dado.cns %></td>

            <td><%= dado.email %></td>

            <td class="white-space-nowrap-center" style="width: 16px">
              <%= link_to_visualizar cadastro_basicos_municipe_path(dado), remote: true %>
              <%= link_to_editar edit_cadastro_basicos_municipe_path(dado) %>
              <%= link_to_excluir cadastro_basicos_municipe_path(dado), remote: true if can? :manage, Admin %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/cadastro_basicos/municipes/new.html.erb
<%= panel_with_form title: label_translate(:new) + translate_model(CadastroBasicos::Municipe) %>

app/views/cadastro_basicos/municipes/new.js.erb
$('#modal_xfull_static').modal();
$("#modal_content_xfull_static").html("<%= escape_javascript(render('form')) %>");

// Add the dialog title
$('#modal_titulo').html("<%= label_translate(:new) + ' ' + singularize_model(CadastroBasicos::Municipe) %>");
resetarComponents();

app/views/cadastro_basicos/municipes/show.js.erb
$('#modal_xfull_static').modal();
$("#modal_content_xfull_static").html("<%= escape_javascript(render('show')) %>");

// Add the dialog title
$('#modal_titulo').html("<%= label_translate(:show) %> <%= singularize_model(CadastroBasicos::Municipe) %>");